FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["EmpowerID/EmpowerID/EmpowerID.EmployeeManagement.csproj", "./EmpowerID/EmployeeManagement/"]
RUN dotnet restore "./EmpowerID/EmployeeManagement/EmpowerID.EmployeeManagement.csproj"
COPY ["EmpowerID/EmpowerID", "./EmpowerID/EmployeeManagement/"]
WORKDIR "/src/EmpowerID/EmployeeManagement"
RUN dotnet build "EmpowerID.EmployeeManagement.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EmpowerID.EmployeeManagement.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EmpowerID.EmployeeManagement.dll"]